[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
temp_project = "G3buTvmMGr4guzRftVvy7YX5s24WARiqEPg2dbo8TPSV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = '~\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
